<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Form\Type;

use PopIn\Model\PopInCampaignQuery;
use Thelia\Core\Form\Type\Field\AbstractIdType;

/**
 * Class PopInCampaign
 * @package PopIn\Form
 */
class PopInCampaignIdType extends AbstractIdType
{
    protected function getQuery()
    {
        return new PopInCampaignQuery();
    }

    public function getName()
    {
        return static::class;
    }
}
