<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Form\Type;

use PopIn\Form\Type\Base\PopInCampaignIdType as BasePopInCampaignIdType;

/**
 * Class PopInCampaign
 * @package PopIn\Form
 */
class PopInCampaignIdType extends BasePopInCampaignIdType
{
}
