<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Event\Module\Base;

/**
 * Class PopInEvents
 * @package PopIn\Event\Module\Base
 * @author TheliaStudio
 */
class PopInEvents
{
    const POP_IN_CAMPAIGN_CREATE = "action.pop_in_campaign.create";
    const POP_IN_CAMPAIGN_UPDATE = "action.pop_in_campaign.update";
    const POP_IN_CAMPAIGN_DELETE = "action.pop_in_campaign.delete";
}
