<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Event;

use PopIn\Event\Base\PopInCampaignEvents as BasePopInCampaignEvents;

/**
 * Class PopInCampaignEvents
 * @package PopIn\Event
 */
class PopInCampaignEvents extends BasePopInCampaignEvents
{
}
