<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Event;

use PopIn\Event\Base\PopInCampaignEvent as BasePopInCampaignEvent;

/**
 * Class PopInCampaignEvent
 * @package PopIn\Event
 */
class PopInCampaignEvent extends BasePopInCampaignEvent
{
}
