<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Form\Base;

use PopIn\Form\PopInCampaignCreateForm as ChildPopInCampaignCreateForm;
use PopIn\Form\Type\PopInCampaignIdType;

/**
 * Class PopInCampaignForm
 * @package PopIn\Form
 * @author TheliaStudio
 */
class PopInCampaignUpdateForm extends ChildPopInCampaignCreateForm
{
    const FORM_NAME = "pop_in_campaign_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", PopInCampaignIdType::TYPE_NAME)
        ;
    }
}
