<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Event\Module;

use PopIn\Event\Module\Base\PopInEvents as BasePopInEvents;

/**
 * Class PopInEvents
 * @package PopIn\Event\Module
 * @author TheliaStudio
 */
class PopInEvents extends BasePopInEvents
{
}
