<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Controller\Base;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Tools\URL;
use PopIn\Event\PopInCampaignEvent;
use PopIn\Event\PopInCampaignEvents;
use PopIn\Model\PopInCampaignQuery;

/**
 * Class PopInCampaignController
 * @package PopIn\Controller\Base
 * @author TheliaStudio
 */
class PopInCampaignController extends AbstractCrudController
{
    public function __construct()
    {
        parent::__construct(
            "pop_in_campaign",
            "id",
            "order",
            AdminResources::MODULE,
            PopInCampaignEvents::CREATE,
            PopInCampaignEvents::UPDATE,
            PopInCampaignEvents::DELETE,
            null,
            null,
            "PopIn"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm()
    {
        return $this->createForm("pop_in_campaign.create");
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array())
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm("pop_in_campaign.update", "form", $data);
    }

    /**
     * Hydrate the update form for this object, before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm($object)
    {
        $data = array(
            "id" => $object->getId(),
            "start" => $object->getStart(),
            "end" => $object->getEnd(),
            "content_source_type" => $object->getContentSourceType(),
            "content_source_id" => $object->getContentSourceId(),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getCreationEvent($formData)
    {
        $event = new PopInCampaignEvent();

        $event->setStart($formData["start"]);
        $event->setEnd($formData["end"]);
        $event->setContentSourceType($formData["content_source_type"]);
        $event->setContentSourceId($formData["content_source_id"]);

        return $event;
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getUpdateEvent($formData)
    {
        $event = new PopInCampaignEvent();

        $event->setId($formData["id"]);
        $event->setStart($formData["start"]);
        $event->setEnd($formData["end"]);
        $event->setContentSourceType($formData["content_source_type"]);
        $event->setContentSourceId($formData["content_source_id"]);

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent()
    {
        $event = new PopInCampaignEvent();

        $event->setId($this->getRequest()->request->get("pop_in_campaign_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event)
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event)
    {
        return $event->getPopInCampaign();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject()
    {
        return PopInCampaignQuery::create()
            ->findPk($this->getRequest()->query->get("pop_in_campaign_id"))
        ;
    }

    /**
     * Returns the object label form the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object)
    {
        return '';
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object)
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder , if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder)
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("pop-in-campaigns");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate()
    {
        $this->getParserContext()
            ->set(
                "pop_in_campaign_id",
                $this->getRequest()->query->get("pop_in_campaign_id")
            )
        ;

        return $this->render("pop-in-campaign-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToEditionTemplate()
    {
        $id = $this->getRequest()->query->get("pop_in_campaign_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/PopIn/pop_in_campaign/edit",
                [
                    "pop_in_campaign_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToListTemplate()
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/PopIn/pop_in_campaign")
        );
    }
}
