<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Event\Base;

use Thelia\Core\Event\ActionEvent;
use PopIn\Model\PopInCampaign;

/**
* Class PopInCampaignEvent
* @package PopIn\Event\Base
* @author TheliaStudio
*/
class PopInCampaignEvent extends ActionEvent
{
    protected $id;
    protected $start;
    protected $end;
    protected $contentSourceType;
    protected $contentSourceId;
    protected $popInCampaign;
    protected $textFree;
    protected $link;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getStart()
    {
        return $this->start;
    }

    public function setStart($start)
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd()
    {
        return $this->end;
    }

    public function setEnd($end)
    {
        $this->end = $end;

        return $this;
    }

    public function getContentSourceType()
    {
        return $this->contentSourceType;
    }

    public function setContentSourceType($contentSourceType)
    {
        $this->contentSourceType = $contentSourceType;

        return $this;
    }

    public function getContentSourceId()
    {
        return $this->contentSourceId;
    }

    public function setContentSourceId($contentSourceId)
    {
        $this->contentSourceId = $contentSourceId;

        return $this;
    }

    public function getPopInCampaign()
    {
        return $this->popInCampaign;
    }

    public function setPopInCampaign(PopInCampaign $popInCampaign)
    {
        $this->popInCampaign = $popInCampaign;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getTextFree()
    {
        return $this->textFree;
    }

    /**
     * @param mixed $textFree
     */
    public function setTextFree($textFree)
    {
        $this->textFree = $textFree;
    }

    /**
     * @return mixed
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * @param mixed $link
     */
    public function setLink($link)
    {
        $this->link = $link;
    }

}
