<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Event\Base;

use PopIn\Event\Module\PopInEvents as ChildPopInEvents;

/*
 * Class PopInCampaignEvents
 * @package PopIn\Event\Base
 * @author TheliaStudio
 */
class PopInCampaignEvents
{
    const CREATE = ChildPopInEvents::POP_IN_CAMPAIGN_CREATE;
    const UPDATE = ChildPopInEvents::POP_IN_CAMPAIGN_UPDATE;
    const DELETE = ChildPopInEvents::POP_IN_CAMPAIGN_DELETE;
}
