<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PopIn\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use PopIn\Model\PopInCampaignQuery;

/**
 * Class PopInCampaign
 * @package PopIn\Form\Base
 * @author TheliaStudio
 */
class PopInCampaignIdType extends AbstractIdType
{
    const TYPE_NAME = "pop_in_campaign_id";

    protected function getQuery()
    {
        return new PopInCampaignQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
